name: ci

on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
  push:
    branches:
      - main

env:
  CACHE_NODE_MODULES_PATH: |
    ~/.npm
    node_modules
  BASE_REF: ${{ github.event_name == 'pull_request' && format('remotes/origin/{0}', github.base_ref) || 'HEAD~1' }}
  RUN_UNIQUE_ID: ${{ github.run_id }}-${{ github.run_attempt }}
  CHROMATIC_LABEL: chromatic
jobs:
  chromatic-prepare:
    runs-on: ubuntu-latest
    outputs:
      storybooks-related-lib-changed: ${{ steps.storybooks-related-lib-changed.outputs.storybooks-related-lib-changed }}
      pr-has-chromatic-label: ${{ steps.pr-has-chromatic-label.outputs.pr-has-chromatic-label }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14.18.1'
#      - uses: actions/cache@v3
#        id: cache
#        with:
#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
#      - name: Install dependencies
#        run: npm ci
#      - name: Check changes "storybook-covered"
#        id: storybooks-related-lib-changed
#        run: echo "::set-output name=storybooks-related-lib-changed::$(node scripts/ci-is-affected.mjs --base=${{ env.BASE_REF }} --head=HEAD --target=storybook-mark)"
      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["chromatic"]'
      - name: Check is PR had the "chromatic" label
        id: pr-has-chromatic-label
        run: echo "::set-output name=pr-has-chromatic-label::${{ steps.check_pr_labels.outputs.result }}"

#  install:
#    runs-on: ubuntu-latest
#    outputs:
#      storybooks-related-lib-changed: ${{ steps.storybooks-related-lib-changed.outputs.storybooks-related-lib-changed }}
#      pr-has-chromatic-label: ${{ steps.pr-has-chromatic-label.outputs.pr-has-chromatic-label }}
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/cache@v3
#        id: cache
#        with:
#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
#      - name: Install dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: npm ci
#      - name: Check changes "storybook-covered"
#        id: storybooks-related-lib-changed
#        run: echo "::set-output name=storybooks-related-lib-changed::$(node scripts/ci-is-affected.mjs --base=${{ env.BASE_REF}} --head=HEAD --target=storybook-mark)"
#      - name: Check PR labels action step
#        id: check_pr_labels
#        uses: shioyang/check-pr-labels-on-push-action@v1.0.6
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          labels: '["chromatic"]'
#      - name: Check is PR had the "chromatic" label
#        id: pr-has-chromatic-label
#        run: echo "::set-output name=pr-has-chromatic-label::${{ steps.check_pr_labels.outputs.result }}"




#          - name: Check PR labels action step
#            id: check_pr_labels
#            uses: shioyang/check-pr-labels-on-push-action@v1.0.6
#            with:
#              github-token: ${{ secrets.GITHUB_TOKEN }}
#              labels: '["chromatic"]'
#          - name: See result
#            run: echo "${{ steps.check_pr_labels.outputs.result }}"

#  check-storybook:
#    needs: chromatic-prepare
#    if: ${{ needs.chromatic-prepare.outputs.storybooks-related-lib-changed == 'true'}}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: actions/cache@v3
#        with:
#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
#
#      - name: check-storybook
#        run: npm run build-storybook

  check-chromatic-PR-label:
    needs: chromatic-prepare
    if: ${{ contains(github.event.pull_request.labels.*.name, $env.CHROMATIC_LABEL) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ This PR potentially has changes covered by storybook. Set a `${{env.CHROMATIC_LABEL}}` label to verify them'
            })

#
#  check-chromatic-pr:
#    needs: check-storybook
#    if: ${{ contains(github.event.pull_request.labels.*.name, 'chromatic') && github.ref != 'refs/heads/main'}}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0 # Required to retrieve git history
#      - uses: actions/cache@v3
#        with:
#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
#
#      #      - run: node scripts/patch-storybook-main.mjs --base=${{env.BASE_REF}} --head=HEAD
#
#      - run: npm run build-storybook
#
#      - run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes  --storybook-build-dir=dist/storybook/ui --only-story-names "ButtonComponent/**"
#
#  apply-chromatic:
#    needs: [chromatic-prepare, check-storybook]
#    if: ${{ github.ref == 'refs/heads/main' && needs.chromatic-prepare.outputs.pr-has-chromatic-label == 'true' }}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0 # Required to retrieve git history
#      - uses: actions/cache@v3
#        with:
#          path: ${{ env.CACHE_NODE_MODULES_PATH }}
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
#
#      #      - run: node scripts/patch-storybook-main.mjs --base=${{env.BASE_REF}} --head=HEAD
#
#      - run: npm run build-storybook
#
#      - run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --auto-accept-changes  --storybook-build-dir=dist/storybook/ui
