name: ci

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci

      - name: test
        run: npm test

#  chromatic-deployment:
#    needs: install
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: node_modules-${{ hashFiles('**/package-lock.json') }}
#
#      - name: test
#        run: npm test
